export default {
    
    SEARCH_REQUEST_START: 'SEARCH_REQUEST_START',
    SEARCH_REQUEST_SUCCESS: 'SEARCH_REQUEST_SUCCESS',
    SEARCH_REQUEST_ERRORED: 'SEARCH_REQUEST_ERRORED',

    CLEAR_FILTERS: 'CLEAR_FILTERS',

    OPEN_BOTTOM_SHEET: 'OPEN_BOTTOM_SHEET',
    CLOSE_BOTTOM_SHEET: 'CLOSE_BOTTOM_SHEET',

    EXAM_ITEMS_MENU: 'EXAM_ITEMS_MENU',

    FETCH_ASSESMENT_ITEM_START: 'FETCH_ASSESMENT_ITEM_START',
    FETCH_ASSESMENT_ITEM_SUCCESS: 'FETCH_ASSESMENT_ITEM_SUCCESS',
    FETCH_ASSESMENT_ITEM_ERRORED: 'FETCH_ASSESMENT_ITEM_ERRORED',

    CREATE_NEW_ASSESMENT_TEST_START: 'CREATE_NEW_ASSESMENT_TEST_START',
    CREATE_NEW_ASSESMENT_TEST_SUCCESS: 'CREATE_NEW_ASSESMENT_TEST_SUCCESS',
    CREATE_NEW_ASSESMENT_TEST_ERRORED: 'CREATE_NEW_ASSESMENT_TEST_ERRORED',

    FETCH_PREVIOUS_TESTS_START: 'FETCH_PREVIOUS_TESTS_START',
    FETCH_PREVIOUS_TESTS_SUCCESS: 'FETCH_PREVIOUS_TESTS_SUCCESS',
    FETCH_PREVIOUS_TESTS_ERRORED: 'FETCH_PREVIOUS_TESTS_ERRORED',

    FETCH_SINGLE_TEST_START: 'FETCH_SINGLE_TEST_START',
    FETCH_SINGLE_TEST_SUCCESS: 'FETCH_SINGLE_TEST_SUCCESS',
    FETCH_SINGLE_TEST_ERRORED: 'FETCH_SINGLE_TEST_ERRORED',

    UPDATE_TEST_START: 'UPDATE_TEST_START',
    UPDATE_TEST_SUCCESS: 'UPDATE_TEST_SUCCESS',
    UPDATE_TEST_ERRORED: 'UPDATE_TEST_ERRORED',

    CREATE_NEW_CLASSROOM_TEST_START: 'CREATE_NEW_CLASSROOM_TEST_START',
    CREATE_NEW_CLASSROOM_TEST_SUCCESS: 'CREATE_NEW_CLASSROOM_TEST_SUCCESS',
    CREATE_NEW_CLASSROOM_TEST_ERRORED: 'CREATE_NEW_CLASSROOM_TEST_ERRORED',

} 