export default {
    
    SEARCH_REQUEST_START: 'SEARCH_REQUEST_START',
    SEARCH_REQUEST_SUCCESS: 'SEARCH_REQUEST_SUCCESS',
    SEARCH_REQUEST_ERRORED: 'SEARCH_REQUEST_ERRORED',

    CLEAR_FILTERS: 'CLEAR_FILTERS',

} 